import React from 'react';
import { Page, Text, View, Document, StyleSheet, Image, Font } from '@react-pdf/renderer';

// Register nice fonts if available, or just use standard ones
// Font.register({ family: 'Roboto', src: 'https://cdnjs.cloudflare.com/ajax/libs/ink/3.1.10/fonts/Roboto/Roboto-Regular.ttf' });

const styles = StyleSheet.create({
    page: {
        flexDirection: 'column',
        backgroundColor: '#FFFFFF',
        padding: 30,
        fontSize: 10,
        fontFamily: 'Helvetica',
    },
    header: {
        marginBottom: 20,
        borderBottom: '2px solid #1A3E5C',
        paddingBottom: 10,
    },
    companyName: {
        fontSize: 20,
        color: '#1A3E5C',
        fontWeight: 'bold',
        marginBottom: 4,
    },
    companyDetails: {
        fontSize: 10,
        color: '#666',
    },
    reportTitle: {
        fontSize: 16,
        color: '#F59E0B',
        fontWeight: 'bold',
        marginTop: 10,
        marginBottom: 4,
        textTransform: 'uppercase',
    },
    reportMeta: {
        fontSize: 10,
        color: '#444',
        marginBottom: 20,
    },
    footer: {
        position: 'absolute',
        bottom: 30,
        left: 30,
        right: 30,
        borderTop: '1px solid #E2E8F0',
        paddingTop: 10,
        flexDirection: 'row',
        justifyContent: 'space-between',
        color: '#999',
        fontSize: 8,
    },
    logo: {
        width: 60,
        height: 60,
        marginBottom: 10,
    }
});

interface ReportPDFProps {
    title: string;
    subTitle?: string;
    companyName?: string;
    companyAddress?: string; // New
    companyGstin?: string; // New
    date?: string;
    orientation?: 'portrait' | 'landscape';
    children: React.ReactNode;
}

export const ReportPDF: React.FC<ReportPDFProps> = ({
    title,
    subTitle,
    companyName = 'Optima Enterprises',
    companyAddress = '123, Business Park, Tech City',
    companyGstin = '37ABCDE1234F1Z5',
    date = new Date().toLocaleDateString(),
    orientation = 'portrait',
    children
}) => (
    <Document>
        <Page size="A4" orientation={orientation} style={styles.page}>
            <View style={styles.header}>
                <Text style={styles.companyName}>{companyName}</Text>

                {/* Dynamic Address Rendering */}
                {companyAddress && (
                    <Text style={styles.companyDetails}>{companyAddress}</Text>
                )}

                {companyGstin && (
                    <Text style={styles.companyDetails}>GSTIN: {companyGstin}</Text>
                )}

                <Text style={styles.reportTitle}>{title}</Text>
                {subTitle && <Text style={{ fontSize: 10, color: '#666' }}>{subTitle}</Text>}
            </View>

            {children}

            <View style={styles.footer}>
                <Text>Generated by LekhyaAI on {new Date().toLocaleString()}</Text>
                <Text render={({ pageNumber, totalPages }) => (
                    `${pageNumber} / ${totalPages}`
                )} fixed />
            </View>
        </Page>
    </Document>
);
